### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chemitaxis** [CL0SeY/aspnet-s3xmlrepository#1]
Hi, did you test this code in a real web app? I'm using [this code](https://github.com/GrabYourPitchforks/DataProtection.Azure/tree/dev) (the same idea but in Azure ), but this code make my web app go down. The code block my threads... very strange behaviour.

Memory dumps when the web app is down is for example (Microsoft support made the analysis):

_As we can see later on, as threads are being added to thread pool, the Task is still not being activated thus leading to a "permanent" hang._ 

_Root of the "performance" issue here is retrieval of some keys (apparently from Azure Blob).  It's being done in a Task, and as far as I can tell this Task has not been spun up yet.  _Currently_ there are no threads to serve that task (as threadpool is maxed out)._

_And by-design, this thread owns a lock and this is blocking ALL other requests._

Thank you so much!

**Comment by CL0SeY** [comment]
Hi there,

Sorry for the late reply!

I have had this code working and have not been aware of any performance impact as yet.

Could you change your line:

```
IList<XElement> elements = Task.Run(() => GetAllElementsAsync(blobRef)).SyncAwait();
```

To use a non-async call or not use Task.Run ? I am not too familiar with the Blob Storage stuff myself.

Cheers.
